resolver: lts-13.9
extra-deps:
- jsonpath-0.1.0.1
- jwt-0.10.0
- katip-0.8.0.0
- git: https://github.com/akshaymankar/haskell-oidc-client
  commit: a8473ac96a6db919f789578a08adaa13a0a3e1d5
packages:
- kubernetes
- kubernetes-client
